[package]
edition = "2024"
name = "xpanse-driver-api"
version = "0.1.0"
license = "GPL-3.0"

[dependencies]
embassy-rp = { workspace = true }
embassy-time = { workspace = true }
embassy-sync = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
defmt = { workspace = true }
embedded-io-async = { workspace = true }
static_cell = { workspace = true }
libm = { workspace = true }
