use alloc::boxed::Box;
use alloc::collections::BTreeMap;
use alloc::vec::Vec;
use core::any::{Any, TypeId};

use crate::metadata::{ModuleID, ModuleSlot};

/// Identifies the physical resource behind a registered logical capability.
///
/// Drivers should use the same `ResourceId` when registering multiple logical
/// capabilities that are backed by the same physical hardware. For example, if
/// one physical button can be used as both `A` and `X`, register both logical
/// button capabilities with the same `ResourceId`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, defmt::Format)]
pub struct ResourceId {
    kind: ResourceIdKind,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, defmt::Format)]
enum ResourceIdKind {
    Physical { slot: ModuleSlot, local_id: u16 },
    Generated(u32),
}

impl ResourceId {
    /// Creates a physical resource id scoped to a module slot.
    ///
    /// The `local_id` only needs to be unique within the module driver for the
    /// given slot. Reuse the same `local_id` for logical capabilities that are
    /// aliases of the same physical resource.
    pub const fn new(slot: ModuleSlot, local_id: u16) -> Self {
        Self {
            kind: ResourceIdKind::Physical { slot, local_id },
        }
    }

    /// Returns the physical `(slot, local_id)` pair for explicitly identified
    /// resources, or `None` for ids generated by [`Registry::register`].
    pub const fn physical_parts(self) -> Option<(ModuleSlot, u16)> {
        match self.kind {
            ResourceIdKind::Physical { slot, local_id } => Some((slot, local_id)),
            ResourceIdKind::Generated(_) => None,
        }
    }

    fn generated(id: u32) -> Self {
        Self {
            kind: ResourceIdKind::Generated(id),
        }
    }
}

pub struct RegisteredResource<T> {
    id: ResourceId,
    slot: ModuleSlot,
    module_id: ModuleID,
    pub resource: T,
}

pub struct CapabilityList<T> {
    items: Vec<RegisteredResource<T>>,
}

impl<T> RegisteredResource<T> {
    pub const fn id(&self) -> ResourceId {
        self.id
    }

    pub const fn slot(&self) -> ModuleSlot {
        self.slot
    }

    pub const fn module_id(&self) -> ModuleID {
        self.module_id
    }
}

impl<T> CapabilityList<T> {
    pub fn iter(&self) -> impl Iterator<Item = &RegisteredResource<T>> {
        self.items.iter()
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }
}

impl<T> Default for CapabilityList<T> {
    fn default() -> Self {
        Self { items: Vec::new() }
    }
}

pub struct Registry {
    entries: BTreeMap<TypeId, Box<dyn Any + Send>>,
    next_generated_resource_id: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, defmt::Format)]
pub enum RegistryError {
    SlotMismatch,
}

impl Default for Registry {
    fn default() -> Self {
        Self::new()
    }
}

impl Registry {
    pub fn new() -> Self {
        Self {
            entries: BTreeMap::new(),
            next_generated_resource_id: 0,
        }
    }

    /// Registers a resource with an automatically generated unique id.
    ///
    /// Use [`Registry::register_with_id`] instead when multiple logical
    /// capabilities are backed by the same physical resource and need to be
    /// recognized as aliases.
    pub fn register<T: 'static + Send>(
        &mut self,
        slot: ModuleSlot,
        module_id: ModuleID,
        resource: T,
    ) {
        let id = ResourceId::generated(self.next_generated_resource_id);
        self.next_generated_resource_id = self
            .next_generated_resource_id
            .checked_add(1)
            .expect("generated resource id counter overflowed");

        self.register_with_id(slot, module_id, id, resource)
            .expect("generated resource IDs do not contain a slot");
    }

    /// Registers a resource with an explicit physical identity.
    ///
    /// Logical capabilities that map to the same physical hardware should share
    /// the same `id`. Apps can then use distinct allocation methods such as
    /// [`Registry::take_distinct2`] to avoid mapping two required functions to
    /// the same physical resource.
    pub fn register_with_id<T: 'static + Send>(
        &mut self,
        slot: ModuleSlot,
        module_id: ModuleID,
        id: ResourceId,
        resource: T,
    ) -> Result<(), RegistryError> {
        if let Some((id_slot, _)) = id.physical_parts()
            && id_slot != slot
        {
            return Err(RegistryError::SlotMismatch);
        }

        self.entries
            .entry(TypeId::of::<CapabilityList<T>>())
            .or_insert_with(|| Box::new(CapabilityList::<T>::default()))
            .downcast_mut::<CapabilityList<T>>()
            .expect("TypeId key guarantees the stored type")
            .items
            .push(RegisteredResource {
                id,
                slot,
                module_id,
                resource,
            });
        Ok(())
    }

    pub fn capabilities<T: 'static + Send>(&self) -> Option<&CapabilityList<T>> {
        self.entries
            .get(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_ref::<CapabilityList<T>>())
    }

    /// Returns how many logical resources of type `T` are currently available.
    pub fn resource_count<T: 'static + Send>(&self) -> usize {
        self.entries
            .get(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_ref::<CapabilityList<T>>())
            .map_or(0, |list| list.items.len())
    }

    /// Returns whether at least one logical resource of type `T` is currently available.
    pub fn has<T: 'static + Send>(&self) -> bool {
        self.has_at_least::<T>(1)
    }

    /// Returns whether at least `count` logical resources of type `T` are currently available.
    pub fn has_at_least<T: 'static + Send>(&self, count: usize) -> bool {
        self.resource_count::<T>() >= count
    }

    /// Returns whether at least `count` resources of type `T` with distinct
    /// physical ids are currently available.
    pub fn has_distinct_resources<T: 'static + Send>(&self, count: usize) -> bool {
        if count == 0 {
            return true;
        }

        let Some(list) = self
            .entries
            .get(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_ref::<CapabilityList<T>>())
        else {
            return false;
        };

        count_distinct_ids(list) >= count
    }

    /// Returns whether one `T` and one `U` can be allocated with different
    /// physical ids.
    ///
    /// This is intended for apps that need two different logical capabilities,
    /// such as `Button<A>` and `Button<X>`, and must not receive two aliases of
    /// the same physical control.
    pub fn has_distinct2<T: 'static + Send, U: 'static + Send>(&self) -> bool {
        if TypeId::of::<T>() == TypeId::of::<U>() {
            return false;
        }

        let Some(left) = self
            .entries
            .get(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_ref::<CapabilityList<T>>())
        else {
            return false;
        };

        let Some(right) = self
            .entries
            .get(&TypeId::of::<CapabilityList<U>>())
            .and_then(|boxed| boxed.downcast_ref::<CapabilityList<U>>())
        else {
            return false;
        };

        distinct_pair_indices(left, right).is_some()
    }

    pub fn return_resource<T: 'static + Send>(&mut self, resource: RegisteredResource<T>) {
        self.register_with_id(
            resource.slot,
            resource.module_id,
            resource.id,
            resource.resource,
        )
        .expect("returned resources retain their original slot");
    }

    pub fn take_resource<T: 'static + Send>(&mut self) -> Option<RegisteredResource<T>> {
        self.entries
            .get_mut(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_mut::<CapabilityList<T>>())
            .and_then(|list| list.items.pop())
    }

    /// Takes exactly `count` logical resources of type `T` if enough are available.
    ///
    /// If fewer than `count` resources are available, the registry is left unchanged.
    pub fn take_resources<T: 'static + Send>(
        &mut self,
        count: usize,
    ) -> Option<Vec<RegisteredResource<T>>> {
        if count == 0 {
            return Some(Vec::new());
        }

        let list = self
            .entries
            .get_mut(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_mut::<CapabilityList<T>>())?;

        if list.items.len() < count {
            return None;
        }

        Some(list.items.split_off(list.items.len() - count))
    }

    /// Takes exactly `count` resources of type `T` with distinct physical ids.
    ///
    /// If fewer than `count` distinct physical resources are available, the
    /// registry is left unchanged.
    pub fn take_distinct_resources<T: 'static + Send>(
        &mut self,
        count: usize,
    ) -> Option<Vec<RegisteredResource<T>>> {
        if count == 0 {
            return Some(Vec::new());
        }

        let indices = {
            let list = self
                .entries
                .get(&TypeId::of::<CapabilityList<T>>())
                .and_then(|boxed| boxed.downcast_ref::<CapabilityList<T>>())?;

            distinct_resource_indices(list, count)?
        };

        let list = self
            .entries
            .get_mut(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_mut::<CapabilityList<T>>())
            .expect("resource list existed while selecting distinct resources");

        let mut resources = Vec::new();
        for index in indices {
            resources.push(list.items.remove(index));
        }

        Some(resources)
    }

    /// Atomically takes one `T` and one `U` with different physical ids.
    ///
    /// If no distinct pair is available, the registry is left unchanged. This
    /// method is for different Rust resource types; use
    /// [`Registry::take_distinct_resources`] when taking multiple resources of
    /// the same type.
    pub fn take_distinct2<T: 'static + Send, U: 'static + Send>(
        &mut self,
    ) -> Option<(RegisteredResource<T>, RegisteredResource<U>)> {
        if TypeId::of::<T>() == TypeId::of::<U>() {
            return None;
        }

        let (left_index, right_index) = {
            let left = self
                .entries
                .get(&TypeId::of::<CapabilityList<T>>())
                .and_then(|boxed| boxed.downcast_ref::<CapabilityList<T>>())?;

            let right = self
                .entries
                .get(&TypeId::of::<CapabilityList<U>>())
                .and_then(|boxed| boxed.downcast_ref::<CapabilityList<U>>())?;

            distinct_pair_indices(left, right)?
        };

        let left = self
            .entries
            .get_mut(&TypeId::of::<CapabilityList<T>>())
            .and_then(|boxed| boxed.downcast_mut::<CapabilityList<T>>())
            .expect("left resource list existed while selecting distinct pair")
            .items
            .remove(left_index);

        let right = self
            .entries
            .get_mut(&TypeId::of::<CapabilityList<U>>())
            .and_then(|boxed| boxed.downcast_mut::<CapabilityList<U>>())
            .expect("right resource list existed while selecting distinct pair")
            .items
            .remove(right_index);

        Some((left, right))
    }
}

fn count_distinct_ids<T>(list: &CapabilityList<T>) -> usize {
    let mut count = 0;

    for index in 0..list.items.len() {
        let id = list.items[index].id;
        if list.items[..index].iter().all(|item| item.id != id) {
            count += 1;
        }
    }

    count
}

fn distinct_resource_indices<T>(list: &CapabilityList<T>, count: usize) -> Option<Vec<usize>> {
    let mut indices: Vec<usize> = Vec::new();

    for index in (0..list.items.len()).rev() {
        let id = list.items[index].id;
        if indices
            .iter()
            .all(|&existing_index| list.items[existing_index].id != id)
        {
            indices.push(index);

            if indices.len() == count {
                return Some(indices);
            }
        }
    }

    None
}

fn distinct_pair_indices<T, U>(
    left: &CapabilityList<T>,
    right: &CapabilityList<U>,
) -> Option<(usize, usize)> {
    for left_index in (0..left.items.len()).rev() {
        for right_index in (0..right.items.len()).rev() {
            if left.items[left_index].id != right.items[right_index].id {
                return Some((left_index, right_index));
            }
        }
    }

    None
}
