use crate::gpio_bank::{BasePin, GpioBank};
use embassy_rp::{
    adc::{AdcChannel, AdcPin},
    i2c,
    pwm::{self, ChannelAPin, ChannelBPin},
    spi, uart,
};

pub trait Driver<
    'a,
    I2C,
    SPI,
    UART,
    PWM_SLICE0,
    PWM_SLICE1,
    PWM_SLICE2,
    GPIO0,
    GPIO1,
    GPIO2,
    GPIO3,
    GPIO4,
    GPIO5,
    GPIO6,
    GPIO7,
    GPIO8,
    GPIO9,
> where
    I2C: i2c::Instance,
    SPI: spi::Instance,
    UART: uart::Instance,
    PWM_SLICE0: pwm::Slice,
    PWM_SLICE1: pwm::Slice,
    PWM_SLICE2: pwm::Slice,
    GPIO0: BasePin + i2c::SclPin<I2C>,
    GPIO1: BasePin + i2c::SdaPin<I2C>,
    GPIO2: BasePin + spi::ClkPin<SPI> + ChannelAPin<PWM_SLICE2>,
    GPIO3: BasePin + spi::MisoPin<SPI>,
    GPIO4: BasePin + spi::MosiPin<SPI>,
    GPIO5: BasePin + uart::TxPin<UART> + ChannelAPin<PWM_SLICE1>,
    GPIO6: BasePin + uart::RxPin<UART> + ChannelBPin<PWM_SLICE1>,
    GPIO7: BasePin + AdcChannel + AdcPin + ChannelAPin<PWM_SLICE0>,
    GPIO8: BasePin + AdcChannel + AdcPin + ChannelBPin<PWM_SLICE0>,
    GPIO9: BasePin,
{
    fn init(
        &mut self,
        gpio_bank: GpioBank<
            'a,
            I2C,
            SPI,
            UART,
            PWM_SLICE0,
            PWM_SLICE1,
            PWM_SLICE2,
            GPIO0,
            GPIO1,
            GPIO2,
            GPIO3,
            GPIO4,
            GPIO5,
            GPIO6,
            GPIO7,
            GPIO8,
            GPIO9,
        >,
    ) -> impl Future<Output = ()>;
}
